# Generated by Django 4.1.4 on 2022-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kutuphane',
            fields=[
                ('konumid', models.AutoField(db_column='konumID', primary_key=True, serialize=False)),
                ('odano', models.IntegerField(db_column='odaNo')),
                ('masano', models.CharField(db_column='MasaNo', max_length=1)),
                ('sandalyeno', models.CharField(db_column='sandalyeNo', max_length=2)),
            ],
            options={
                'db_table': 'kutuphane',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Misafiruye',
            fields=[
                ('uyeid', models.AutoField(db_column='UyeID', primary_key=True, serialize=False)),
                ('ad', models.CharField(db_column='Ad', max_length=45)),
                ('soyad', models.CharField(db_column='Soyad', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=45, unique=True)),
                ('sifre', models.CharField(db_column='Sifre', max_length=8)),
                ('meslek', models.CharField(blank=True, db_column='Meslek', max_length=45, null=True)),
                ('telno', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'misafiruye',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ogrenciuye',
            fields=[
                ('uyeid', models.AutoField(db_column='uyeID', primary_key=True, serialize=False)),
                ('ad', models.CharField(db_column='Ad', max_length=40)),
                ('soyad', models.CharField(db_column='Soyad', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=45, unique=True)),
                ('sifre', models.CharField(db_column='Sifre', max_length=8)),
                ('telno', models.CharField(blank=True, db_column='Telno', max_length=45, null=True)),
                ('puan', models.IntegerField(blank=True, db_column='Puan', null=True)),
                ('ogrno', models.IntegerField(db_column='OgrNo', unique=True)),
                ('fakulte', models.CharField(blank=True, db_column='Fakulte', max_length=45, null=True)),
                ('bolum', models.CharField(blank=True, db_column='Bolum', max_length=45, null=True)),
                ('mezuntarihi', models.DateField(blank=True, db_column='MezunTarihi', null=True)),
            ],
            options={
                'db_table': 'ogrenciuye',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oneri',
            fields=[
                ('oneriid', models.AutoField(db_column='oneriID', primary_key=True, serialize=False)),
                ('oneri', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oneri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('rezervasyonid', models.AutoField(db_column='rezervasyonID', primary_key=True, serialize=False)),
                ('tarih', models.DateField()),
                ('saatbaslangic', models.TimeField(db_column='saatBaslangic')),
                ('saatbitis', models.TimeField(db_column='saatBitis')),
                ('molahakki', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rezervasyon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('siparisid', models.AutoField(db_column='siparisID', primary_key=True, serialize=False)),
                ('siparistarih', models.DateTimeField(db_column='siparisTarih')),
                ('teslimtarih', models.DateTimeField(db_column='teslimTarih')),
            ],
            options={
                'db_table': 'siparis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siparisurun',
            fields=[
                ('siparisid', models.IntegerField(db_column='siparisID', primary_key=True, serialize=False)),
                ('urunid', models.IntegerField(db_column='urunID')),
            ],
            options={
                'db_table': 'siparisurun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('urunid', models.AutoField(db_column='urunID', primary_key=True, serialize=False)),
                ('urunismi', models.CharField(db_column='urunIsmi', max_length=45)),
                ('urunpuan', models.IntegerField(blank=True, db_column='urunPuan', null=True)),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('urunfotografadi', models.CharField(blank=True, db_column='urunFotografadi', max_length=50, null=True)),
            ],
            options={
                'db_table': 'urun',
                'managed': False,
            },
        ),
    ]
